### FILE: R/generateCovNames.R ###

#' Generate and Format Covariate Labels for Forest Plots
#'
#' @description 
#' Dynamically constructs covariate names from a forest plot covariate data frame.
#' If \code{dfres} is provided, it safely maps these generated labels directly onto the 
#' results data frame using the \code{COVNUM} relational key, returning the updated data frame.
#' 
#' It features an interactive two-step workflow: run with \code{print_template = TRUE}
#' to generate a boilerplate mapping script in the console, then fill it out and
#' pass the maps back in to append units, replace categorical labels, or format group headers.
#'
#' @param dfCovs A data frame containing covariate scenarios (must have a \code{COVARIATEGROUPS} column).
#' @param dfres An optional results data frame generated by \code{\link{getForestDFFREM}} 
#'   or \code{\link{getExplainedVar}}. If provided, the function returns this data frame 
#'   with the \code{COVNAME} and \code{GROUPNAME} columns updated and safely factored.
#' @param unit_map A named character vector for appending units (e.g., \code{c(WT = "kg")}).
#' @param label_map A named character vector for exact replacements (e.g., \code{c("SEX=1" = "Male")}).
#' @param group_map A named character vector for replacing covariate group names 
#'   (e.g., \code{c("WT" = "Weight", "SEX" = "Sex")}).
#' @param print_template Logical. If \code{TRUE}, prints an R script template to the console and exits.
#'
#' @return If \code{dfres} is \code{NULL}, returns a character vector of formatted covariate names.
#'   If \code{dfres} is provided, returns the updated \code{dfres} data frame containing factored 
#'   \code{COVNAME} and \code{GROUPNAME} columns.
#' 
#' @family Diagnostics & Plotting Internal
#' @concept diagnostics
#' @export
#'
#' @examples
#' # 1. Create a synthetic forest plot covariate dataframe
#' dfCovs <- data.frame(
#'   COVARIATEGROUPS = c("WT", "WT", "SEX", "SEX"),
#'   WT = c(70, 90, -99, -99),
#'   SEX = c(-99, -99, 1, 2)
#' )
#' 
#' # 2. Create a synthetic results dataframe
#' dfres <- data.frame(
#'   COVNUM = c(1, 2, 3, 4),
#'   PARAMETER = rep("CL", 4),
#'   VALUE = c(1.1, 1.3, 0.9, 1.0)
#' )
#' 
#' # 3. Define Translation Maps
#' unit_map <- c(WT = "kg")
#' label_map <- c("SEX=1" = "Male", "SEX=2" = "Female")
#' group_map <- c("WT" = "Body Weight", "SEX" = "Biological Sex")
#' 
#' # --- Example A: Extract Character Vector ---
#' # Returns standard formatted strings for covariate names
#' generateCovNames(dfCovs, unit_map = unit_map, label_map = label_map)
#' 
#' # --- Example B: Relational Data Frame Mapping ---
#' # Safely mutates the data frame, adding locked COVNAME and GROUPNAME factors
#' dfres_updated <- generateCovNames(
#'   dfCovs, 
#'   dfres = dfres, 
#'   unit_map = unit_map, 
#'   label_map = label_map,
#'   group_map = group_map
#' )
#' 
#' print(dfres_updated)
generateCovNames <- function(dfCovs, dfres = NULL, unit_map = NULL, label_map = NULL, group_map = NULL, print_template = FALSE) {
  if (!"COVARIATEGROUPS" %in% names(dfCovs)) {
    stop("dfCovs must contain a 'COVARIATEGROUPS' column.", call. = FALSE)
  }
  
  # 1. Extract Base Strings and Groups
  groups <- as.character(dfCovs$COVARIATEGROUPS)
  base_strings <- sapply(seq_len(nrow(dfCovs)), function(i) {
    grp <- groups[i]
    
    if (grp %in% names(dfCovs)) {
      return(paste0(grp, "=", dfCovs[[grp]][i]))
    }
    
    pattern <- paste0("^", grp, "_")
    dummy_cols <- grep(pattern, names(dfCovs), value = TRUE)
    
    if (length(dummy_cols) == 0) {
      warning(paste("No matching columns found for covariate group:", grp), call. = FALSE)
      return(paste0(grp, "=UNKNOWN"))
    }
    
    suffixes <- as.numeric(gsub(pattern, "", dummy_cols))
    row_vals <- as.numeric(dfCovs[i, dummy_cols, drop = FALSE])
    
    if (any(row_vals == 1, na.rm = TRUE)) {
      val <- suffixes[which(row_vals == 1)[1]]
    } else {
      val <- min(suffixes, na.rm = TRUE) - 1
    }
    return(paste0(grp, "=", val))
  })
  
  # 2. Template Generation Mode
  if (print_template) {
    u_groups <- unique(groups)
    u_base <- unique(base_strings)
    
    cat("# Copy and paste this mapping template into your script:\n\n")
    
    cat("group_map <- c(\n")
    cat(paste0("  \"", u_groups, "\" = \"\""), sep = ",\n")
    cat("\n)\n\n")
    
    cat("unit_map <- c(\n")
    cat(paste0("  \"", u_groups, "\" = \"\""), sep = ",\n")
    cat("\n)\n\n")
    
    cat("label_map <- c(\n")
    cat(paste0("  \"", u_base, "\" = \"\""), sep = ",\n")
    cat("\n)\n")
    
    return(invisible(NULL))
  }
  
  # 3. Application Mode (Row-level labels)
  res <- sapply(seq_along(base_strings), function(i) {
    b <- base_strings[i]
    g <- groups[i]
    
    # Label Replacement (Categorical) takes precedence
    if (!is.null(label_map) && b %in% names(label_map)) {
      if (label_map[[b]] != "") return(label_map[[b]])
    }
    
    # Unit Appending (Continuous)
    if (!is.null(unit_map) && g %in% names(unit_map)) {
      if (unit_map[[g]] != "") return(paste0(b, " ", unit_map[[g]]))
    }
    
    return(b)
  })
  
  # 4. Relational Data Frame Mapping
  if (!is.null(dfres)) {
    if (!"COVNUM" %in% names(dfres)) {
      stop("The provided dfres must contain a 'COVNUM' column to securely map the labels.", call. = FALSE)
    }
    
    # Map the row labels securely using the row index indicator
    mapped_labels <- res[dfres$COVNUM]
    dfres$COVNAME <- factor(mapped_labels, levels = unique(res))
    
    # Map the group headers securely
    mapped_groups <- sapply(groups, function(g) {
      if (!is.null(group_map) && g %in% names(group_map) && group_map[[g]] != "") {
        return(group_map[[g]])
      }
      return(g)
    })
    
    # Apply as a factor to lock the group plotting order
    mapped_groups_expanded <- mapped_groups[dfres$COVNUM]
    dfres$GROUPNAME <- factor(mapped_groups_expanded, levels = unique(mapped_groups))
    
    return(dfres)
  }
  
  return(as.character(res))
}