#' Calculate the explained variability for covariates in a FREM model.
#'
#' Get a data frame with explainable variability information based on a dataset
#' of subjects with covariates
#'
#' The total variability of the metric (e.g. a primary or secondary parameter)
#' is derived from the FREM model from the estimated multivariate OMEGA matrix,
#' estimated EBEs, or sampled ETAs from the estimated multivariate OMEGA matrix,
#' and setting the FREM covariate coefficients to zero. There are four
#' alternatives that can be requested via the type argument.
#'
#' **type=0:** Use the the delta rule (FO approximation) to derive the total variability
#' of the metric across the involved omegas. The first row in dfCovs is used for values of
#' any FFEM covariates.
#'
#' **type=1:** Use the estimated EBEs and calculate the variance of the desired
#' metric across the individuals in the data set. Requires etas or a phi-file
#' associated with the model. The default method to calculate the total
#' variability.
#'
#' **type=2:** Use numETASamples sampled eta vectors from the
#' estimated multivariate omega matrix to compute numETASamples values of the
#' metric. The total variability is the average (over all individuals) of the
#' variances of the numETASamples values of the metrics.
#'
#' **type=3:** Use numETASamples sampled eta vectors from the
#' estimated multivariate omega matrix to compute numETASamples values of the
#' metric for one individual (the first) in the data set. The total variability
#' is the variance of the numETASamples values of the metric.
#'
#' If there are no FFEM covariate relationships in the model, then type 2 and 3
#' are identical, but type=3 will be faster.
#'
#' type=0 will be fast but not always accurate.
#'
#' type=1 will also be relatively fast and handles FFEM covariates, but is
#' sensitive to shrinkage and small data sets.
#'
#' type=2 is the slowest way to calculate the total variability but handles FFEM
#' covariates and is not sensitive to shrinkage.
#'
#' type=3 is not sensitive to shrinkage and is preferred over type=2 if there
#' are no FFEM covariates.
#'
#' @param type How the total variability should be derived. See Details.

#' @param data the data.frame with dataset to base the explained variability
#'   on, used with type=1-3
#' @param dfCovs A data frame with covariates to based the variability plots on
#' @param dfext a data frame with the final estimates in a ext-file format
#' @param strID the subject identifier in the dfCovs dataset, default='ID'
#' @inheritParams getFileNames
#' @param cstrCovariates A string vector with names of the covariates that
#'   should be investigated, i.e. must have the same length as the number of
#'   rows in dfCovs. If NULL then COV1, COV2 etc. will be used.
#' @param functionList Can either be a list of functions with input (basethetas,
#'   covthetas,dfrow and ...) for which the explained variability will be
#'   calculated, or a function that returns a vector of values. , each value will be
#'   used but functionListName must contain the names with a length of all
#'   return for all functions in the functionList
#' @param functionListName A vector of strings (names) for the parameters generated by functionList.
#' @param numNonFREMThetas Number of structural thetas in FREM model
#' @param numFREMThetas Number of covariate thetas in FREM model
#' @param numSigmas Number of sigmas in FREM model
#' @param numParCov Number of parameters for which covariate relations are
#'   sought (often the same as numNonFREMThetas).
#' @param numSkipOm Number of Omegas that are not associated with FREM
#'   covariates, i.e. skip before calculating the FREM varianes, default= 0
#' @param parNames Names of the parameters
#' @param availCov Names of the covariates to use in the calculation of the FFEM
#'   model, default=NULL (use all covariates)
#' @param etas the etas used to calculate the explained variability, used with
#'   type=1 and should be the same size as number of individuals in data. If
#'   `NULL` when type=1 the estas will be obtained from the phi-file.
#' @param quiet If output should be allowed during the function call, default=
#'   FALSE,
#' @param ncores the number of cores to use for the calculations, default = 1
#'   which means no parallellization
#' @param cstrPackages a character vector with the packages needed to run
#'   calculations in parallel, default = NULL
#' @param cstrExports a character vector with variables needed to run the
#'   calculations in parallel, default = NULL
#' @param numETASamples (default = 100) the number of samples used ot integrate
#'   over individual parameters when calculating the total variance of the
#'   functionList, only used using type==2 & type==3
#' @param seed (default = -1 = random, used when sampling ETAs in type==2 and
#'   type==3)
#' @param ... additional variables to be forwarded to the the functionList
#'   functions
#'
#' @return A data frame with summary statistics for each parameters and
#'   covariate combinations. There will be one row for each parameter-covariate
#'   combination + one row for each partameter with the combination of all
#'   covariates.
#'
#' * COVNUM: The covariate number. Repeated per PARAMETER. 1 is the explained variability of All covariates.
#' * COVNAME: The name of the covariate as specified in the original data set.
#' * PARAMETER: The name(s) of the parameter(s).
#' * TOTVAR: The total variability according to `type`. Repeated for each parameter-covariate combination.
#' * TOTCOVVAR: The total variability explained when all covariates are used.Repeated for each parameter-covariate combination.
#' * COVVAR: The variability explained by each covariate by itself.
#'
#' @export
#'
#' @details
#' The \code{availCov} argument specifies the covariates in the frem model that should be used for the calculations
#' of the maximum variability (TOTCOVVAR). If NULL (default), all covariates inteh frem model will be used for the derivation of TOTCOVVAR.
#'
#' @examples
#' 
#' \donttest{
#' modDevDir <- system.file("extdata/SimNeb",package="PMXFrem")
#' fremRunno <- 31
#' modFile   <- file.path(modDevDir,paste0("run",fremRunno,".mod"))
#' covNames  <- getCovNames(modFile = modFile)
#'
#' ## Set up dfCovs
#' dfData <- read.csv(system.file("extdata/SimNeb/DAT-2-MI-PMX-2-onlyTYPE2-new.csv", package = "PMXFrem")) %>%
#'   filter(BLQ == 0) %>%
#'   distinct(ID,.keep_all = TRUE)
#'
#' dfCovs <- setupdfCovs(modFile)
#'
#' cstrCovariates <- c("All",names(dfCovs))
#'
#' ## A list of functions
#' functionList2 <- list(
#'   function(basethetas,covthetas, dfrow, etas, ...){ return(basethetas[2]*exp(covthetas[1] + etas[3]))},
#'   function(basethetas,covthetas, dfrow, etas, ...){ return(basethetas[3]*exp(covthetas[2] + etas[4]))}
#' )
#'
#' functionListName2 <- c("CL","V")
#'
#' dfres1 <- getExplainedVar(type             = 1,
#'                           data             = dfData,
#'                           dfCovs           = dfCovs,
#'                           numNonFREMThetas = 7,
#'                           numSkipOm        = 2,
#'                           functionList     = functionList2,
#'                           functionListName = functionListName2,
#'                           cstrCovariates   = cstrCovariates,
#'                           modDevDir        = modDevDir,
#'                           runno            = fremRunno,
#'                           ncores           = 2,
#'                           quiet            = TRUE,
#'                           seed             = 123
#' )
#'
#' ## A function that returns a vector of values
#' vectorFunction <- function(basethetas,covthetas, dfrow, etas, ...) {
#'   return(
#'     c(basethetas[2]*exp(covthetas[1] + etas[3]),
#'       basethetas[3]*exp(covthetas[2] + etas[4]))
#' )
#' }
#'
#' dfres12 <- getExplainedVar(type            = 0,
#'                           data             = dfData,
#'                           dfCovs           = dfCovs,
#'                           numNonFREMThetas = 7,
#'                           numSkipOm        = 2,
#'                           functionList     = list(vectorFunction), # Need to enclose the function in list()
#'                           functionListName = functionListName2,
#'                           cstrCovariates   = cstrCovariates,
#'                           modDevDir        = modDevDir,
#'                           runno            = fremRunno,
#'                           ncores           = 2,
#'                           quiet            = TRUE,
#'                           seed             = 123
#' )
#' }
#' @family Diagnostics & Plotting
#' @concept diagnostics


getExplainedVar <- function(
    type             = 1,
    data,
    dfCovs,
    dfext            = NULL,
    strID            = "ID",
    runno            = NULL,
    modName          = NULL,
    modDevDir        = ".",
    cstrCovariates   = NULL,
    functionList     = list(function(basethetas, covthetas, dfrow, etas, ...) {
      return(basethetas[1] * exp(covthetas[1] + etas[1]))
    }),
    functionListName = "PAR1",
    numNonFREMThetas,
    numFREMThetas    = NULL,
    numSigmas        = NULL,
    numParCov        = NULL,
    parNames         = NULL,
    numSkipOm        = 0,
    availCov         = NULL,
    etas             = NULL,
    quiet            = FALSE,
    ncores           = 1,
    cstrPackages     = NULL,
    cstrExports      = NULL,
    numETASamples    = 100,
    seed             = NULL,
    ...) {

  if (type > 0 && is.null(data)) stop("data can not be missing with type 1-3.")

  if (type > 0 && !is.null(data)) {
    data <- as.data.frame(data)
  }
  
  fileNames <- getFileNames(runno = runno, modName = modName, modDevDir = modDevDir, ...)
  modFile   <- fileNames$mod
  extFile   <- fileNames$ext
  phiFile   <- fileNames$phi

  if (is.null(dfext)) {
    dfext   <- getExt(extFile = extFile)
  }

  if (nrow(dfext) > 1) dfext <- dfext[dfext$ITERATION == -1000000000, ]
  thetas <- as.numeric(dfext[2:(numNonFREMThetas + 1)])
  
  if (is.null(numFREMThetas)) {
    numFREMThetas <- length(grep("THETA", names(dfext))) - numNonFREMThetas
  }
  
  if (is.null(numSigmas)) {
    numSigmas <- length(grep("SIGMA", names(dfext)))
  }

  ## Check that cstrCovariates has the same length as the number of rows in dfCovs
  if (is.null(cstrCovariates)) {
    cstrCovariates <- paste0("COV", 1:nrow(dfCovs))
  } else {
    if (length(cstrCovariates) != nrow(dfCovs)) {
      stop("cstrCovariates must have the same length as the number of rows in dfCovs")
    }
  }

  if (is.null(parNames)) {
    if (is.null(numParCov)) {
      iNumOmega <- length(grep("OMEGA", names(dfext)))
      numTotEta <- -1 / 2 + sqrt(1 / 4 + 2 * iNumOmega)
      numParCov <- numTotEta - numSkipOm - numFREMThetas
    }
    parNames <- paste("Par", 1:numParCov, sep = "")
  }

  if (type == 1 && is.null(etas)) {
    dfPhi   <- getPhi(phiFile)
    etas    <- dfPhi[, 3:(2 + numParCov + numSkipOm)] # Include the structural model etas only
  }

  if (!is.null(seed))
    set.seed(seed)

  CN       <- getCovNames(modFile)
  fremCovs <- CN$polyCatCovs
  orgCovs  <- CN$orgCovNames
  covNames <- CN$covNames

  ## Sort out the logic for availCov. allCov will indicate the covariates to base TOTCOVVAR on
  if(is.null(availCov)) {
    allCov <- covNames
  } else {
    allCov <- availCov
  }

  if (type==2) {
    if (length(dfCovs)<=length(orgCovs)) {
      warning("Presence of FFEM covariates is indicated (trough type=2), make sure that all FFEM covariates are also available in dfCovs")
    }
  }


  ## Do the calculations
  if (type == 0) {
    return(.calc_fo_variance(
      dfCovs = dfCovs, functionList = functionList, functionListName = functionListName, cstrCovariates = cstrCovariates,
      thetas = thetas, dfext = dfext, numNonFREMThetas = numNonFREMThetas, numFREMThetas = numFREMThetas, numSigmas = numSigmas,
      numParCov = numParCov, numSkipOm = numSkipOm, parNames = parNames, covNames = covNames, allCov = allCov, 
      fremCovs = fremCovs, quiet = quiet, ...
    ))
  }
  
  if (type %in% c(1, 2, 3)) {
    return(.calc_empirical_variance(
      type = type, data = data, dfCovs = dfCovs, dfext = dfext, strID = strID, runno = runno, modName = modName, 
      modDevDir = modDevDir, cstrCovariates = cstrCovariates, functionList = functionList, functionListName = functionListName, 
      numNonFREMThetas = numNonFREMThetas, numFREMThetas = numFREMThetas, numSigmas = numSigmas, numParCov = numParCov, 
      parNames = parNames, numSkipOm = numSkipOm, allCov = allCov, etas = etas, quiet = quiet, ncores = ncores, 
      cstrPackages = cstrPackages, cstrExports = cstrExports, numETASamples = numETASamples, seed = seed, 
      thetas = thetas, covNames = covNames, fremCovs = fremCovs, orgCovs = orgCovs, ...
    ))

  }
  
  stop("Invalid 'type' specified. Must be 0, 1, 2, or 3.")
}
