### FILE: R/plotCovDist.R ###

#' Plot the distribution of estimated FREM covariates by missingness
#'
#' @description 
#' Generates diagnostic distribution plots (histograms or density plots) of the 
#' estimated covariates from a FREM model. The distributions are grouped and colored 
#' by whether the covariate was missing in the original clinical dataset. This helps 
#' evaluate if the model's empirical Bayes estimates for missing covariates map 
#' consistently to the observed cohort's marginal distribution.
#' 
#' Note: In FREM, all estimated covariates are continuous. Therefore, covariates 
#' that were originally binary/categorical will be plotted on a continuous scale.
#'
#' @param df A data frame generated by \code{\link{calcEtas}} (run with 
#'   \code{appendMissingFlags = TRUE}).
#' @param covNames A character vector specifying one or more covariates to plot 
#'   (e.g., \code{c("WT", "AGE")}).
#' @param plotType Character string specifying the geometry. Either \code{"histogram"} 
#'   (default) or \code{"density"}. Note that density plots are scaled to show counts 
#'   on the y-axis to match histograms.
#' @param xlab Character string for the x-axis title. Defaults to 
#'   \code{"Estimated Covariate Value"}.
#' @param ylab Character string for the y-axis title. Defaults to \code{"Count"}.
#' @param fillNonMissing Character string (hex code or color name) for the fill 
#'   of non-missing data. Defaults to \code{"#005B65"} (dark teal).
#' @param fillMissing Character string (hex code or color name) for the fill 
#'   of missing data. Defaults to \code{"#E1A178"} (peach).
#' @param colorOutline Character string for the outline of the geoms. Defaults 
#'   to \code{"white"}.
#' @param alpha Numeric. The transparency of the fills. Defaults to \code{0.6}.
#' @param bins Integer. Number of bins to use if \code{plotType = "histogram"}. 
#'   Defaults to \code{30}.
#' @param scales Character string to control axis scaling across facets. Options are 
#'   \code{"fixed"}, \code{"free"}, \code{"free_x"} (default), or \code{"free_y"}.
#' @param nrow Integer. Number of rows for the facet grid layout. Defaults to \code{NULL}.
#' @param ncol Integer. Number of columns for the facet grid layout. Defaults to \code{NULL}.
#' @param ... Additional arguments passed directly to \code{geom_histogram()} or 
#'   \code{geom_density()} (e.g., \code{linewidth}, \code{bw}).
#'
#' @return A \code{ggplot} object.
#' @export
#'
#' @examples
#' library(PMXFrem)
#' library(ggplot2)
#' 
#' # 1. Prepare data and base model directories
#' model_dir <- system.file("extdata/SimNeb/", package = "PMXFrem")
#' data_path <- system.file("extdata/SimNeb/DAT-2-MI-PMX-2-onlyTYPE2-new.csv", package = "PMXFrem")
#' my_data <- read.csv(data_path)
#' my_data <- my_data[my_data$BLQ != 1, ]
#' 
#' # 2. Generate the individual ETAs and missingness flags
#' ind_params <- calcEtas(
#'   modName            = "run31",
#'   modDevDir          = model_dir,
#'   numNonFREMThetas   = 7,
#'   numSkipOm          = 2,
#'   dataFile           = my_data,
#'   parNames           = c("CL", "V", "MAT"),
#'   appendMissingFlags = TRUE
#' )
#' 
#' # 3. Plot a single covariate distribution (Histogram)
#' p1 <- plotCovDist(ind_params, covNames = "WT")
#' print(p1)
#' 
#' # 4. Plot multiple covariates simultaneously (Density curves of counts)
#' # Forcing a 2-column layout
#' p2 <- plotCovDist(
#'   df = ind_params, 
#'   covNames = c("WT", "AGE", "GENO2","AST"), 
#'   scales = "free",
#'   ncol = 2
#' )
#' print(p2)
#' 
#' @family Diagnostics & Plotting
#' @concept diagnostics
plotCovDist <- function(
    df,
    covNames,
    plotType         = c("histogram", "density"),
    xlab             = "Estimated Covariate Value",
    ylab             = "Count",
    fillNonMissing   = "#005B65",
    fillMissing      = "#E1A178",
    colorOutline     = "white",
    alpha            = 1,
    bins             = 30,
    scales           = "free_x",
    nrow             = NULL,
    ncol             = NULL,
    ...
) {
  
  plotType <- match.arg(plotType)
  
  # --- 1. Input Validation ---
  if (!inherits(df, "data.frame")) {
    stop("`df` must be a data frame generated by calcEtas().", call. = FALSE)
  }
  
  missing_covs <- setdiff(covNames, names(df))
  if (length(missing_covs) > 0) {
    stop("The following requested covariates are not in the data frame: ", 
         paste(missing_covs, collapse = ", "), call. = FALSE)
  }
  
  # Check for Missingness Flags
  miss_cols <- paste0(covNames, "_MISSING")
  missing_flags <- setdiff(miss_cols, names(df))
  if (length(missing_flags) > 0) {
    warning(sprintf("Missingness flags not found for: %s. Plotting all these points as 'Non-missing'. To fix this, run calcEtas() with `appendMissingFlags = TRUE`.", 
                    paste(gsub("_MISSING", "", missing_flags), collapse = ", ")), call. = FALSE)
    for (mf in missing_flags) {
      df[[mf]] <- 0 # Default to Non-missing
    }
  }
  
  # --- 2. Data Wrangling (Pivot to Long Format) ---
  
  # Isolate and pivot the covariate values
  df_covs <- df %>%
    dplyr::select(ID, dplyr::all_of(covNames)) %>%
    tidyr::pivot_longer(cols = -ID, names_to = "Covariate", values_to = "Value")
  
  # Isolate and pivot the missingness flags
  df_miss <- df %>%
    dplyr::select(ID, dplyr::all_of(miss_cols)) %>%
    dplyr::rename_with(~ sub("_MISSING$", "", .), dplyr::ends_with("_MISSING")) %>%
    tidyr::pivot_longer(cols = -ID, names_to = "Covariate", values_to = "Missing_Flag")
  
  # Join them together to align the value perfectly with its respective flag
  plot_df <- dplyr::left_join(df_covs, df_miss, by = c("ID", "Covariate")) %>%
    dplyr::mutate(
      Missingness = factor(
        ifelse(.data$Missing_Flag == 1, "Missing", "Non-missing"),
        levels = c("Non-missing", "Missing")
      )
    )
  
  # --- 3. Plotting ---
  fill_mapping <- stats::setNames(
    c(fillNonMissing, fillMissing), 
    c("Non-missing", "Missing")
  )
  
  p <- ggplot2::ggplot(plot_df, ggplot2::aes(x = .data$Value, fill = .data$Missingness))
  
  if (plotType == "histogram") {
    p <- p + ggplot2::geom_histogram(
      position = "identity", 
      color = colorOutline, 
      alpha = alpha, 
      bins = bins, 
      ...
    )
  } else {
    # Scale density to show counts on the y-axis to match the requested y-axis behavior
    p <- p + ggplot2::geom_density(
      ggplot2::aes(y = ggplot2::after_stat(count)),
      color = colorOutline, 
      alpha = alpha, 
      ...
    )
  }
  
  # Faceting: wraps for 1 or more covariates, scales and row/col parameters applied here
  p <- p + 
    ggplot2::scale_fill_manual(values = fill_mapping) +
    ggplot2::facet_wrap(~ Covariate, scales = scales, nrow = nrow, ncol = ncol) +
    ggplot2::labs(x = xlab, y = ylab) +
    ggplot2::theme_bw() +
    ggplot2::theme(
      legend.position = "top",
      legend.direction = "horizontal",
      legend.title = ggplot2::element_blank(),
      strip.background = ggplot2::element_rect(fill = "gray95")
    )
  
  return(p)
}