### FILE: R/plotEtasCov.R ###

#' Plot FREM ETAs and ETA_prims against a specified covariate
#'
#' @description 
#' Generates a diagnostic scatter plot with a smoothing line, comparing the base 
#' FREM ETAs and ETA_prims against a specified covariate. The plot is faceted by 
#' the ETA type (columns) and the calculation method (Prim vs. FREM, rows). 
#' It automatically colors points based on whether the covariate was missing in 
#' the original clinical dataset.
#'
#' @param df A data frame generated by \code{\link{calcEtas}} (run with 
#'   \code{appendMissingFlags = TRUE}).
#' @param covName A character string specifying the name of the covariate to 
#'   plot on the x-axis (e.g., \code{"WT"}).
#' @param etaNames A character vector of structural ETAs to include in the plot 
#'   (e.g., \code{c("ETA3", "ETA4")}). If \code{NULL} (default), all columns matching 
#'   the regex \code{"^ETA[0-9]+$"} will be automatically detected and plotted.
#' @param xlab Character string for the x-axis title. Defaults to \code{covName}.
#' @param ylab Character string for the y-axis title. Defaults to \code{"Value"}.
#' @param colorNonMissing Character string (hex code or color name) for non-missing 
#'   points. Defaults to \code{"#005B65"} (dark teal).
#' @param colorMissing Character string (hex code or color name) for missing points. 
#'   Defaults to \code{"#E1A178"} (peach).
#' @param pointShape Integer. The ggplot2 shape code for the points. Defaults to \code{16}.
#' @param pointSize Numeric. The size of the points. Defaults to \code{1.5}.
#' @param pointAlpha Numeric. The transparency of the points. Defaults to \code{1}.
#' @param smoothMethod Character string. The smoothing method to use (e.g., \code{"loess"}, 
#'   \code{"lm"}). Defaults to \code{"loess"}.
#' @param smoothColor Character string for the smoothing line color. Defaults to \code{"black"}.
#' @param smoothLinetype Character string for the smoothing line type. Defaults to \code{"solid"}.
#' @param smoothSize Numeric. The thickness of the smoothing line. Defaults to \code{1}.
#' @param smoothSe Logical. Display confidence interval around smooth? Defaults to \code{FALSE}.
#' @param ... Additional arguments passed directly to \code{ggplot2::geom_smooth()} 
#'   (e.g., \code{span}, \code{formula}).
#'
#' @return A \code{ggplot} object.
#' @export
#'
#' @examples
#' \dontrun{
#' library(PMXFrem)
#' library(ggplot2)
#' 
#' # 1. Define the path to the model files included with the package
#' model_dir <- system.file("extdata/SimNeb/", package = "PMXFrem")
#' 
#' # 2. Load and prepare the dataset also included with the package
#' data_path <- system.file("extdata/SimNeb/DAT-2-MI-PMX-2-onlyTYPE2-new.csv", package = "PMXFrem")
#' my_data <- read.csv(data_path)
#' my_data <- my_data[my_data$BLQ != 1, ] # Exclude BLQ rows
#' 
#' # 3. Generate the individual ETAs and missingness flags
#' ind_params <- calcEtas(
#'   modName            = "run31",
#'   modDevDir          = model_dir,
#'   numNonFREMThetas   = 7,
#'   numSkipOm          = 2,
#'   dataFile           = my_data,
#'   parNames           = c("CL", "V", "MAT"),
#'   ffemModName        = "run31max0",
#'   appendMissingFlags = TRUE
#' )
#' 
#' # 4. Plot the ETAs vs Weight (WT)
#' # By default, it will auto-detect all ETAs and the WT_MISSING flag
#' p1 <- plotEtasCov(df = ind_params, covName = "WT")
#' print(p1)
#' 
#' # 5. Customized plot restricting to specific ETAs with a linear trend line
#' p2 <- plotEtasCov(
#'   df = ind_params, 
#'   covName = "WT", 
#'   etaNames = c("ETA3", "ETA4"),
#'   xlab = "Weight (kg)", 
#'   ylab = "Empirical Bayes Estimate",
#'   smoothMethod = "lm", 
#'   smoothColor = "blue",
#'   smoothLinetype = "dashed"
#' )
#' print(p2)
#' }
#' 
#' @family Diagnostics & Plotting
#' @concept diagnostics
plotEtasCov <- function(
    df,
    covName,
    etaNames         = NULL,
    xlab             = covName,
    ylab             = "Value",
    colorNonMissing  = "#005B65",
    colorMissing     = "#E1A178",
    pointShape       = 16,
    pointSize        = 1.5,
    pointAlpha       = 1,
    smoothMethod     = "loess",
    smoothColor      = "black",
    smoothLinetype   = "solid",
    smoothSize       = 1,
    smoothSe         = FALSE,
    ...
) {
  
  # --- 1. Input Validation ---
  if (!inherits(df, "data.frame")) {
    stop("`df` must be a data frame generated by calcEtas().", call. = FALSE)
  }
  if (!covName %in% names(df)) {
    stop(sprintf("Covariate '%s' not found in the provided data frame.", covName), call. = FALSE)
  }
  
  # Auto-detect ETAs if not explicitly provided
  if (is.null(etaNames)) {
    etaNames <- grep("^ETA[0-9]+$", names(df), value = TRUE)
    if (length(etaNames) == 0) {
      stop("Could not auto-detect any ETA columns (e.g., 'ETA1'). Please specify them using the `etaNames` argument.", call. = FALSE)
    }
  } else {
    missing_etas <- setdiff(etaNames, names(df))
    if (length(missing_etas) > 0) {
      stop("The following requested ETAs are not in the data frame: ", paste(missing_etas, collapse = ", "), call. = FALSE)
    }
  }
  
  # Check for corresponding ETA_PRIM columns
  prim_names <- paste0(etaNames, "_PRIM")
  missing_prims <- setdiff(prim_names, names(df))
  if (length(missing_prims) > 0) {
    stop("Missing corresponding PRIM columns for the requested ETAs: ", paste(missing_prims, collapse = ", "), call. = FALSE)
  }
  
  # Check for Missingness Flag
  miss_col <- paste0(covName, "_MISSING")
  if (!miss_col %in% names(df)) {
    warning(sprintf("Missingness flag '%s' not found. Plotting all points as 'Non-missing'. To fix this, run calcEtas() with `appendMissingFlags = TRUE`.", miss_col), call. = FALSE)
    df[[miss_col]] <- 0 # Default all to 0 (Non-missing) if missing
  }
  
  # --- 2. Data Wrangling ---
  # Extract Base FREM ETAs
  df_frem <- df %>%
    dplyr::select(dplyr::all_of(etaNames), dplyr::all_of(covName), dplyr::all_of(miss_col)) %>%
    tidyr::pivot_longer(cols = dplyr::all_of(etaNames), names_to = "ETA", values_to = "values") %>%
    dplyr::mutate(Type = "FREM")
  
  # Extract ETA_PRIMs and rename to match base ETAs for clean vertical faceting
  df_prim <- df %>%
    dplyr::select(dplyr::all_of(prim_names), dplyr::all_of(covName), dplyr::all_of(miss_col)) %>%
    dplyr::rename_with(~ etaNames, dplyr::all_of(prim_names)) %>%
    tidyr::pivot_longer(cols = dplyr::all_of(etaNames), names_to = "ETA", values_to = "values") %>%
    dplyr::mutate(Type = "Prim")
  
  # Combine and convert missing flag to an explicit factor
  plot_df <- dplyr::bind_rows(df_prim, df_frem) %>%
    dplyr::mutate(
      Missingness = factor(
        ifelse(.data[[miss_col]] == 1, "Missing", "Non-missing"),
        levels = c("Non-missing", "Missing")
      )
    )
  
  # --- 3. Plotting ---
  # Named vector to guarantee colors assign correctly even if one level is missing
  color_mapping <- stats::setNames(
    c(colorNonMissing, colorMissing), 
    c("Non-missing", "Missing")
  )
  
  p <- ggplot2::ggplot(plot_df, ggplot2::aes(x = .data[[covName]], y = .data$values)) +
    ggplot2::geom_point(ggplot2::aes(color = .data$Missingness), 
                        shape = pointShape, size = pointSize, alpha = pointAlpha) +
    ggplot2::geom_smooth(method = smoothMethod, color = smoothColor, 
                         linetype = smoothLinetype, linewidth = smoothSize, 
                         se = smoothSe, ...) +
    ggplot2::scale_color_manual(values = color_mapping) +
    ggplot2::facet_grid(Type ~ ETA) +
    ggplot2::labs(x = xlab, y = ylab) +
    ggplot2::theme_bw() +
    ggplot2::theme(
      legend.position = "top",
      legend.direction = "horizontal",
      legend.title = ggplot2::element_blank()
    )
  
  return(p)
}