### FILE: R/plotEtasCov.R ###

#' Plot FREM ETAs and ETA_prims against a specified covariate
#'
#' @description 
#' Generates a diagnostic scatter plot comparing selected ETA estimates 
#' (FREM ETA, ETA_prim, and/or FFEM EBE) against a specified covariate.
#' 
#' By default, this function plots only the observed covariates, filtering out 
#' missing data to fit a smoothing line exclusively to the true observations. 
#' Visualizing missing covariates is available as an option to evaluate the 
#' model's handling of missing data.
#'
#' @param df A data frame generated by \code{\link{calcEtas}}. To visualize missingness, 
#'   this must be run with \code{appendMissingFlags = TRUE}.
#' @param covName A character string specifying the name of the covariate to 
#'   plot on the x-axis (e.g., \code{"WT"}).
#' @param etaNames A character vector of structural ETAs to include in the plot 
#'   (e.g., \code{c("ETA3", "ETA4")}). If \code{NULL} (default), all columns matching 
#'   the regex \code{"^ETA[0-9]+$"} will be automatically detected.
#' @param etaTypes A character vector specifying which types of ETAs to plot.
#'   Allowed values are \code{"FREM"}, \code{"Prim"}, and \code{"EBE"}. Defaults to 
#'   \code{c("FREM", "Prim")}. The order specified determines the top-to-bottom facet row order.
#' @param etaLabels A character vector of custom labels for the ETA columns.
#'   Must be the same length as \code{etaNames}. If \code{NULL} (default), \code{etaNames} are used.
#' @param typeLabels A named character vector specifying custom labels for the ETA 
#'   calculation types (the facet rows). Defaults to \code{c("FREM" = "FREM ETA", 
#'   "Prim" = "ETA Prim", "EBE" = "FFEM EBE")}.
#' @param showMissing Logical. If \code{FALSE} (default), subjects with missing 
#'   covariate data are excluded from the plot. If \code{TRUE}, they are visualized.
#' @param smoothNonMissing Logical. If \code{TRUE} (default), draws a smoothing line 
#'   through the non-missing observed data.
#' @param smoothMissing Logical. If \code{TRUE}, draws a smoothing line through the 
#'   missing data. Defaults to \code{FALSE}.
#' @param xlab Character string for the x-axis title. Defaults to \code{covName}.
#' @param ylab Character string for the y-axis title. Defaults to \code{"Value"}.
#' @param colorNonMissing Character string (hex code or color name) for non-missing 
#'   points. Defaults to \code{"#005B65"} (dark teal).
#' @param colorMissing Character string (hex code or color name) for missing points.
#'   Defaults to \code{"#E1A178"} (peach).
#' @param pointShape Integer. The ggplot2 shape code for the points. Defaults to \code{16}.
#' @param pointSize Numeric. The size of the points. Defaults to \code{1.5}.
#' @param pointAlpha Numeric. The transparency of the points. Defaults to \code{1}.
#' @param smoothMethod Character string. The smoothing method to use (e.g., \code{"loess"}, 
#'   \code{"lm"}). Defaults to \code{"loess"}.
#' @param smoothColor Character string for the observed smoothing line color. Defaults to \code{"black"}.
#' @param smoothLinetype Character string for the smoothing line type. Defaults to \code{"solid"}.
#' @param smoothMissingLinetype Character string for the missing data smoothing line type. Defaults to \code{"dashed"}.
#' @param smoothSize Numeric. The thickness of the smoothing line. Defaults to \code{1}.
#' @param smoothSe Logical. Display confidence interval around smooth? Defaults to \code{FALSE}.
#' @param ... Additional arguments passed directly to \code{ggplot2::geom_smooth()}.
#'
#' @return A \code{ggplot} object.
#' @export
#'
#' @examples
#' library(PMXFrem)
#' library(ggplot2)
#' 
#' # 1. Prepare data and base model directories
#' model_dir <- system.file("extdata/SimNeb/", package = "PMXFrem")
#' data_path <- system.file("extdata/SimNeb/DAT-2-MI-PMX-2-onlyTYPE2-new.csv", package = "PMXFrem")
#' 
#' # Isolate valid observations (e.g., exclude BLQ)
#' my_data <- read.csv(data_path)
#' my_data <- my_data[my_data$BLQ != 1, ] 
#' 
#' # 2. Generate the individual ETAs and missingness flags
#' ind_params <- calcEtas(
#'   modName            = "run31",
#'   modDevDir          = model_dir,
#'   numNonFREMThetas   = 7,
#'   numSkipOm          = 2,
#'   dataFile           = my_data,
#'   parNames           = c("CL", "V", "MAT"),
#'   ffemModName        = "run31max0",
#'   appendMissingFlags = TRUE
#' )
#' 
#' # 3. Example A: Default Diagnostic Plot
#' # Excludes missing covariates to evaluate the observed relationship
#' p_strict <- plotEtasCov(
#'   df = ind_params, 
#'   covName = "WT", 
#'   etaNames = c("ETA3", "ETA4"),
#'   etaTypes = c("EBE", "FREM"),
#'   etaLabels = c("Clearance", "Volume"),
#'   typeLabels = c("EBE" = "FFEM EBE", "FREM" = "FREM EBE")
#' )
#' print(p_strict)
#' 
#' # 4. Example B: Diagnostic Plot with Missing Data
#' # Visualizes missing covariates and fits a separate smoothing line for them
#' p_missing <- plotEtasCov(
#'   df = ind_params, 
#'   covName = "WT", 
#'   etaNames = c("ETA3"),
#'   etaTypes = c("FREM"),
#'   showMissing = TRUE,
#'   smoothMissing = TRUE,
#'   smoothMissingLinetype = "solid",
#'   smoothColor = "#005B65"
#' )
#' print(p_missing)
#'
#' @family Diagnostics & Plotting
#' @concept diagnostics
plotEtasCov <- function(
    df,
    covName,
    etaNames         = NULL,
    etaTypes         = c("FREM", "Prim"),
    etaLabels        = NULL,
    typeLabels       = c("FREM" = "FREM ETA", "Prim" = "ETA Prim", "EBE" = "FFEM EBE"),
    showMissing      = FALSE,
    smoothNonMissing = TRUE,
    smoothMissing    = FALSE,
    xlab             = covName,
    ylab             = "Value",
    colorNonMissing  = "#005B65",
    colorMissing     = "#E1A178",
    pointShape       = 16,
    pointSize        = 1.5,
    pointAlpha       = 1,
    smoothMethod     = "loess",
    smoothColor      = "black",
    smoothLinetype   = "solid",
    smoothMissingLinetype = "dashed",
    smoothSize       = 1,
    smoothSe         = FALSE,
    ...
) {
  
  # Ensure valid inputs and preserve the user's requested order
  etaTypes <- match.arg(etaTypes, choices = c("FREM", "Prim", "EBE"), several.ok = TRUE)
  ordered_levels <- unname(typeLabels[etaTypes])
  
  # --- 1. Input Validation ---
  if (!inherits(df, "data.frame")) {
    stop("`df` must be a data frame generated by calcEtas().", call. = FALSE)
  }
  if (!covName %in% names(df)) {
    stop(sprintf("Covariate '%s' not found in the provided data frame.", covName), call. = FALSE)
  }
  
  # Auto-detect ETAs if not explicitly provided
  if (is.null(etaNames)) {
    etaNames <- grep("^ETA[0-9]+$", names(df), value = TRUE)
    if (length(etaNames) == 0) {
      stop("Could not auto-detect any ETA columns. Please specify them using `etaNames`.", call. = FALSE)
    }
  } else {
    missing_etas <- setdiff(etaNames, names(df))
    if (length(missing_etas) > 0) {
      stop("The following requested ETAs are not in the data frame: ", paste(missing_etas, collapse = ", "), call. = FALSE)
    }
  }
  
  if (is.null(etaLabels)) {
    etaLabels <- etaNames
  } else if (length(etaLabels) != length(etaNames)) {
    stop("`etaLabels` must have the exact same length as `etaNames`.", call. = FALSE)
  }
  
  # Check for Missingness Flag
  miss_col <- paste0(covName, "_MISSING")
  if (!miss_col %in% names(df)) {
    if (showMissing) {
      warning(sprintf("Missingness flag '%s' not found. Cannot differentiate missing data. Run calcEtas() with `appendMissingFlags = TRUE`.", miss_col), call. = FALSE)
    }
    df[[miss_col]] <- 0 # Default all to 0 (Non-missing)
  }
  
  # --- 2. Data Wrangling ---
  plot_data_list <- list()
  
  # Process FREM ETAs
  if ("FREM" %in% etaTypes) {
    plot_data_list[["FREM"]] <- df %>%
      dplyr::select(dplyr::all_of(etaNames), dplyr::all_of(covName), dplyr::all_of(miss_col)) %>%
      tidyr::pivot_longer(cols = dplyr::all_of(etaNames), names_to = "ETA", values_to = "values") %>%
      dplyr::mutate(Type = unname(typeLabels["FREM"]))
  }
  
  # Process ETA Prims
  if ("Prim" %in% etaTypes) {
    prim_names <- paste0(etaNames, "_PRIM")
    missing_prims <- setdiff(prim_names, names(df))
    if (length(missing_prims) > 0) stop("Missing PRIM columns for requested ETAs.", call. = FALSE)
    
    plot_data_list[["Prim"]] <- df %>%
      dplyr::select(dplyr::all_of(prim_names), dplyr::all_of(covName), dplyr::all_of(miss_col)) %>%
      dplyr::rename_with(~ etaNames, dplyr::all_of(prim_names)) %>%
      tidyr::pivot_longer(cols = dplyr::all_of(etaNames), names_to = "ETA", values_to = "values") %>%
      dplyr::mutate(Type = unname(typeLabels["Prim"]))
  }
  
  # Process FFEM EBEs
  if ("EBE" %in% etaTypes) {
    ebe_names <- paste0("EBE_", etaNames)
    missing_ebes <- setdiff(ebe_names, names(df))
    if (length(missing_ebes) > 0) stop("Missing EBE columns. Run calcEtas() with ffemModName.", call. = FALSE)
    
    plot_data_list[["EBE"]] <- df %>%
      dplyr::select(dplyr::all_of(ebe_names), dplyr::all_of(covName), dplyr::all_of(miss_col)) %>%
      dplyr::rename_with(~ etaNames, dplyr::all_of(ebe_names)) %>%
      tidyr::pivot_longer(cols = dplyr::all_of(etaNames), names_to = "ETA", values_to = "values") %>%
      dplyr::mutate(Type = unname(typeLabels["EBE"]))
  }
  
  # Combine, format factors, and filter observations if needed
  plot_df <- dplyr::bind_rows(plot_data_list) %>%
    dplyr::mutate(
      Missingness = factor(
        ifelse(.data[[miss_col]] == 1, "Missing", "Non-missing"),
        levels = c("Non-missing", "Missing")
      ),
      Type = factor(.data$Type, levels = ordered_levels),
      ETA = factor(.data$ETA, levels = etaNames, labels = etaLabels)
    )
  
  if (!showMissing) {
    plot_df <- plot_df %>% dplyr::filter(.data$Missingness == "Non-missing")
  }
  
  # --- 3. Plotting ---
  color_mapping <- stats::setNames(
    c(colorNonMissing, colorMissing), 
    c("Non-missing", "Missing")
  )
  
  # Base mapping
  p <- ggplot2::ggplot(plot_df, ggplot2::aes(x = .data[[covName]], y = .data$values)) +
    ggplot2::geom_point(ggplot2::aes(color = .data$Missingness), 
                        shape = pointShape, size = pointSize, alpha = pointAlpha) +
    ggplot2::scale_color_manual(values = color_mapping, drop = FALSE) +
    ggplot2::facet_grid(Type ~ ETA) +
    ggplot2::labs(x = xlab, y = ylab) +
    ggplot2::theme_bw() +
    ggplot2::theme(
      legend.position = "top",
      legend.direction = "horizontal",
      legend.title = ggplot2::element_blank()
    )
  
  # Add smoothing line for non-missing data
  if (smoothNonMissing) {
    df_non_missing <- plot_df[plot_df$Missingness == "Non-missing", ]
    if (nrow(df_non_missing) > 0) {
      p <- p + ggplot2::geom_smooth(
        data = df_non_missing,
        method = smoothMethod, color = smoothColor, 
        linetype = smoothLinetype, linewidth = smoothSize, 
        se = smoothSe, ...
      )
    }
  }
  
  # Add smoothing line for missing data
  if (showMissing && smoothMissing) {
    df_missing <- plot_df[plot_df$Missingness == "Missing", ]
    if (nrow(df_missing) > 0) {
      p <- p + ggplot2::geom_smooth(
        data = df_missing,
        method = smoothMethod, color = colorMissing, 
        linetype = smoothMissingLinetype, linewidth = smoothSize, 
        se = smoothSe, ...
      )
    }
  }
  
  return(p)
}